sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20539
  redis:
    host: localhost
    port: 6379
    database: 10

# bitiful config
bitiful:
  endpoint: https://s3.bitiful.net/
  region: cn-north-1
  access-key: NhTO08uy7nW5hIHgr8DutyLdg0iwWDo
  secret-key: bLpoXfctiPoIGKEYWRkGZgzD
  bucket-name: worlt-pic/sky-take-away